# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interaction_strength.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(208, 340)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(28, 300, 150, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 201, 291))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Kaa_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kaa_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kaa_value.setObjectName("Kaa_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Kaa_value)
        self.Kba_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kba_label.setObjectName("Kba_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Kba_label)
        self.Kba_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kba_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kba_value.setObjectName("Kba_value")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Kba_value)
        self.Kaa_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kaa_label.setObjectName("Kaa_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Kaa_label)
        self.Kda_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kda_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kda_value.setObjectName("Kda_value")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Kda_value)
        self.Kda_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kda_label.setObjectName("Kda_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Kda_label)
        self.Kab_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kab_label.setObjectName("Kab_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Kab_label)
        self.Kbb_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kbb_label.setObjectName("Kbb_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Kbb_label)
        self.Kdb_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kdb_label.setObjectName("Kdb_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Kdb_label)
        self.Kad_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kad_label.setObjectName("Kad_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Kad_label)
        self.Kbd_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kbd_label.setObjectName("Kbd_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Kbd_label)
        self.Kdd_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Kdd_label.setObjectName("Kdd_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.Kdd_label)
        self.Kab_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kab_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kab_value.setObjectName("Kab_value")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Kab_value)
        self.Kbb_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kbb_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kbb_value.setObjectName("Kbb_value")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Kbb_value)
        self.Kdb_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kdb_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kdb_value.setObjectName("Kdb_value")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Kdb_value)
        self.Kad_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kad_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kad_value.setObjectName("Kad_value")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.Kad_value)
        self.Kbd_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kbd_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kbd_value.setObjectName("Kbd_value")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.Kbd_value)
        self.Kdd_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Kdd_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Kdd_value.setObjectName("Kdd_value")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.Kdd_value)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Kaa_value.setText(_translate("Dialog", "1"))
        self.Kba_label.setText(_translate("Dialog", "Kba"))
        self.Kba_value.setText(_translate("Dialog", "0.1"))
        self.Kaa_label.setText(_translate("Dialog", "Kaa"))
        self.Kda_value.setText(_translate("Dialog", "1"))
        self.Kda_label.setText(_translate("Dialog", "Kda"))
        self.Kab_label.setText(_translate("Dialog", "Kab"))
        self.Kbb_label.setText(_translate("Dialog", "Kbb"))
        self.Kdb_label.setText(_translate("Dialog", "Kdb"))
        self.Kad_label.setText(_translate("Dialog", "Kad"))
        self.Kbd_label.setText(_translate("Dialog", "Kbd"))
        self.Kdd_label.setText(_translate("Dialog", "Kdd"))
        self.Kab_value.setText(_translate("Dialog", "-10"))
        self.Kbb_value.setText(_translate("Dialog", "1"))
        self.Kdb_value.setText(_translate("Dialog", "1"))
        self.Kad_value.setText(_translate("Dialog", "-1"))
        self.Kbd_value.setText(_translate("Dialog", "-1"))
        self.Kdd_value.setText(_translate("Dialog", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
